version: "3"

services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: 'dev_user'
      POSTGRES_DB: 'dev_db'
      POSTGRES_PASSWORD: 'dev_password'
    ports:
      - "5432:5432"
