version: "3"

services:
  app:
    image: zhiyanfoo/rt-editor-app
    ports:
      - "80:80"
    deploy:
      restart_policy:
        condition: on-failure
  http:
    image: zhiyanfoo/rt-editor-http
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: backend
      POSTGRES_DB: rtdoc
      POSTGRES_PASSWORD: {{ $postgres_password }}
      APP_ORIGIN: {{ $app_origin }}
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "5001:5001"
  websocket:
    image: zhiyanfoo/rt-editor-websocket
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: backend
      POSTGRES_DB: rtdoc
      POSTGRES_PASSWORD: {{ $postgres_password }}
      PORT: 5000
    ports:
      - "5000:5000"
    deploy:
      restart_policy:
        condition: on-failure
  # Ideally shouldn't run db in container.
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: backend
      POSTGRES_DB: rtdoc
      POSTGRES_PASSWORD: {{ $postgres_password }}
